#!/bin/bash
file=assignment.zip

# remove old assignment
if [ -f $file ] ; then
    rm $file
fi 

# make a copy of README as instruction so TA can read it
cp README.md instruction.txt
# zip all the files
zip -r $file bin json_objects public routes views app.js package.json package-lock.json README.md instruction.txt
# remove the instruction file because it's useless
rm instruction.txt