#!/bin/bash
file=webkeepers.zip

# remove old assignment
if [ -f $file ] ; then
    rm $file
fi 

# make a copy of README as instruction so TA can read it
cp README.md instruction.txt
# zip all the files
git archive -o $file HEAD
# remove the instruction file because it's useless
rm instruction.txt